import { Player } from './interfaces'

const players: Player[] = [
  {
    nickName: 'Oscare',
    rating: 1.75,
    team: 'NOVA',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'Header',
    rating: 1.52,
    team: 'Quazars',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Modest',
    rating: 1.44,
    team: 'NOVA',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Olaph',
    rating: 1.43,
    team: 'OG',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'Niko',
    rating: 1.43,
    team: 'NOVA',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'bait',
    rating: 1.39,
    team: 'NOVA',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Xantares',
    rating: 1.36,
    team: 'Quazars',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'Collector',
    rating: 1.36,
    team: 'Vangard',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Nelo',
    rating: 1.34,
    team: 'OG',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Refresh',
    rating: 1.33,
    team: 'NOVA',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Rossander',
    rating: 1.3,
    team: 'OG',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Rain',
    rating: 1.28,
    team: 'Quazars',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Focus',
    rating: 1.27,
    team: 'OG',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Salivan',
    rating: 1.26,
    team: 'Island',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'Fury',
    rating: 1.25,
    team: 'Vangard',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Kscerato',
    rating: 1.25,
    team: 'Vangard',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'Torin',
    rating: 1.24,
    team: 'OG',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Tenor',
    rating: 1.24,
    team: 'Vangard',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Wong',
    rating: 1.24,
    team: 'Island',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Cicada',
    rating: 1.23,
    team: 'Solid',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Stoic',
    rating: 1.23,
    team: 'Vangard',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Syrson',
    rating: 1.22,
    team: 'Island',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'LoseIt',
    rating: 1.22,
    team: 'Jupiter',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Tabsen',
    rating: 1.2,
    team: 'Quazars',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Cloudy',
    rating: 1.2,
    team: 'Quazars',
    experience: 0,
    role: 'Lurker',
  },
  {
    nickName: 'Boros',
    rating: 1.2,
    team: 'Island',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Kipito',
    rating: 1.19,
    team: 'TopGun',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Leon',
    rating: 1.18,
    team: 'Jupiter',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Kosus',
    rating: 1.18,
    team: 'TopGun',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Maden',
    rating: 1.18,
    team: 'TopGun',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'Mandarin',
    rating: 1.17,
    team: 'Solid',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Raven',
    rating: 1.17,
    team: 'Jupiter',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Faker',
    rating: 1.26,
    team: 'TopGun',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Soul',
    rating: 1.25,
    team: 'TopGun',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Faris',
    rating: 1.25,
    team: 'Solid',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'Melon',
    rating: 1.24,
    team: 'Island',
    experience: 0,
    role: 'Support',
  },
  {
    nickName: 'Forest',
    rating: 1.24,
    team: 'Jupiter',
    experience: 0,
    role: 'Capitan',
  },
  {
    nickName: 'LoseIt',
    rating: 1.24,
    team: 'Solid',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Somewhere',
    rating: 1.23,
    team: 'Solid',
    experience: 0,
    role: 'Fragger',
  },
  {
    nickName: 'Tabar',
    rating: 1.23,
    team: 'Jupiter',
    experience: 0,
    role: 'Support',
  },
]

export default players
