import { Player } from './interfaces'

const playersDefault: Player[] = [
  {
    nickName: 'Oscare',
    rating: 1.32,
    team: 'NOVA',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Header',
    rating: 1.31,
    team: 'Quazars',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Modest',
    rating: 1.29,
    team: 'NOVA',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Olaph',
    rating: 1.28,
    team: 'Eagles',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Newton',
    rating: 1.28,
    team: 'NOVA',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Roller',
    rating: 1.25,
    team: 'Quazars',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Collector',
    rating: 1.24,
    team: 'Vangard',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Nelo',
    rating: 1.23,
    team: 'Eagles',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Bait',
    rating: 1.2,
    team: 'NOVA',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Brad',
    rating: 1.22,
    team: 'Guardians',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Silver',
    rating: 1.22,
    team: 'University',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Colour',
    rating: 1.22,
    team: 'University',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Octopus',
    rating: 1.21,
    team: 'Five',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Rossander',
    rating: 1.2,
    team: 'Eagles',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Awesome',
    rating: 1.2,
    team: 'Dream',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'NBF',
    rating: 1.2,
    team: 'Moon',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Scelt',
    rating: 1.2,
    team: 'Dream',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Cloudy',
    rating: 1.2,
    team: 'Quazars',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'B8Loo',
    rating: 1.19,
    team: 'Youth',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Serpe',
    rating: 1.18,
    team: 'Quazars',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Lancar',
    rating: 1.18,
    team: 'Canoe',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Macro',
    rating: 1.18,
    team: 'Sempra',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Zoom',
    rating: 1.18,
    team: 'Dream',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Smith',
    rating: 1.17,
    team: 'NOVA',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Focus',
    rating: 1.17,
    team: 'Eagles',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Invincible',
    rating: 1.17,
    team: 'Moon',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Dach',
    rating: 1.17,
    team: 'Canoe',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Theater',
    rating: 1.17,
    team: 'Sempra',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Salivan',
    rating: 1.16,
    team: 'Island',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Faker',
    rating: 1.16,
    team: 'Kadagan',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Boxer',
    rating: 1.16,
    team: 'Five',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Gepard',
    rating: 1.16,
    team: 'Sempra',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Super',
    rating: 1.16,
    team: 'Canoe',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Fury',
    rating: 1.15,
    team: 'Vangard',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Pretios',
    rating: 1.15,
    team: 'Vangard',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Soul',
    rating: 1.15,
    team: 'Kadagan',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Faris',
    rating: 1.15,
    team: 'Solid',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Electron',
    rating: 1.15,
    team: 'Moon',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Crowley',
    rating: 1.15,
    team: 'Guardians',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Right',
    rating: 1.15,
    team: 'Guardians',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Bad',
    rating: 1.15,
    team: 'University',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Phantom',
    rating: 1.15,
    team: 'Canoe',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Titan',
    rating: 1.15,
    team: 'Five',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Swan',
    rating: 1.15,
    team: 'Quazars',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: '1lery',
    rating: 1.14,
    team: 'Eagles',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Tenor',
    rating: 1.14,
    team: 'Vangard',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Wong',
    rating: 1.14,
    team: 'Island',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Melon',
    rating: 1.14,
    team: 'Island',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Forest',
    rating: 1.14,
    team: 'Jupiter',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'LoseIt',
    rating: 1.14,
    team: 'Solid',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Rosh',
    rating: 1.14,
    team: 'Five',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Chellen',
    rating: 1.14,
    team: 'Five',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Chin',
    rating: 1.14,
    team: 'Moon',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Tatam',
    rating: 1.14,
    team: 'Youth',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Aziraphale',
    rating: 1.14,
    team: 'University',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'FGod',
    rating: 1.14,
    team: 'Youth',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Cicada',
    rating: 1.13,
    team: 'Solid',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Stoic',
    rating: 1.13,
    team: 'Vangard',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Somewhere',
    rating: 1.13,
    team: 'Solid',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Tabar',
    rating: 1.13,
    team: 'Jupiter',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Omega',
    rating: 1.13,
    team: 'Sempra',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Timely',
    rating: 1.13,
    team: 'University',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Rock',
    rating: 1.13,
    team: 'Sempra',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Sound',
    rating: 1.13,
    team: 'Guardians',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Dunk',
    rating: 1.12,
    team: 'Island',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'LoseIt',
    rating: 1.12,
    team: 'Jupiter',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Chicago',
    rating: 1.12,
    team: 'Canoe',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Percent',
    rating: 1.12,
    team: 'Youth',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Invisible',
    rating: 1.11,
    team: 'Kadagan',
    experience: 0,
    role: 'Capitan',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Ouroboros',
    rating: 1.1,
    team: 'Island',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Uppper',
    rating: 1.1,
    team: 'Moon',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'SuperFrag',
    rating: 1.1,
    team: 'Guardians',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Catcher',
    rating: 1.1,
    team: 'Dream',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Kipito',
    rating: 1.09,
    team: 'Kadagan',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Salute',
    rating: 1.09,
    team: 'Youth',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Leon',
    rating: 1.08,
    team: 'Jupiter',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Kosus',
    rating: 1.08,
    team: 'Kadagan',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'TheOwl',
    rating: 1.08,
    team: 'Dream',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Mandarin',
    rating: 1.07,
    team: 'Solid',
    experience: 0,
    role: 'Support',
    motivation: 0,
    tactic: 0,
  },
  {
    nickName: 'Raven',
    rating: 1.07,
    team: 'Jupiter',
    experience: 0,
    role: 'Fragger',
    motivation: 0,
    tactic: 0,
  },
]

export default playersDefault
